### ISSUE TITLE
Editor Closes Unexpectedly

### ISSUE THREAD

**Issue by JonPeltier** [fernandreu/office-ribbonx-editor#67] opened 2019-10-30 14:43 UTC
When I finish editing the custom UI of a document and close that document, the entire Editor application closes, rather than staying open with no documents loaded.

**Comment by fernandreu** [comment] 2019-10-30 17:27
This is probably a duplicate of #57, which is fixed in the [latest development build](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=466&view=artifacts). Could you try that version and see if it works as expected?

Otherwise, if this happens because of a crash, the most recent versions of the tool should hopefully give you an error message when something like this occurs, with some informative text that you can paste here for me to debug.

**Comment by celiasja** [comment] 2019-10-30 22:04
Hi, Jon. I had that same issue. In my case, I got it solved when I moved my
files out of Dropbox where I was saving them.

**Comment by JonPeltier** [comment] 2019-10-30 22:21
I use Dropbox for some of my work, but not the add-in I was working on when I finally decided to report the issue.

I installed the 1.5.1.466 dev version and the unexpected closing of the application stopped. However, with this version I could not see the customUI xml code in the code window, though it was listed in the treeview. The icons I'd inserted also were visible in the treeview. Just to make sure, I closed the add-in and opened it in Excel; the buttons were present on the ribbon, so the xml must still be intact.

I'll revert to the 1.5.1.418 production version.

**Comment by fernandreu** [comment] 2019-10-31 07:40
Yes, now the editor is multi-tab and you have to double-click a file (or right click -> open) to show it on the right side. I thought this would be a bit more intuitive, as that is how the majority of multi-tab programs that I know of work.

With this, tabs won't start opening unintentionally when navigating through the treeview. This was reasonably fine in the previous single-editor layout because you would eventually open the file you were interested in, and none of the intermediate files selected would be shown. However, if it worked like this now, you might end up with tabs open that you are not really interested in editing.

Once I make an official release (after I polish a few more things) I will put some notes about this to try to make it as clear as possible.

At some point, I might do something similar to what Visual Studio Code does:

- Single click: show a tab temporarily which will be automatically closed as soon as you select a different item
- Double click: show a tab permanently that you will have to close manually

**Comment by JonPeltier** [comment] 2019-10-31 14:06
Okay, thanks, the need to double click was not obvious, but I can get used to it.

Issues I had:

When only one tab is open, but several files are listed in the treeview, the tab label "customUI.xml" is not sufficient to identify which file's xml is being viewed (I know the active one is highlighted in the treeview, but my eyes are getting old). The filename should appear in the tab label when there are multiple files listed, even if only one is open.

I can have a file listed multiple times in the treeview: the program doesn't check if the file is already in the treeview. This seems to be wrong.

**Comment by JonPeltier** [comment] 2019-11-01 12:12
If I have the same file open twice, and I save (not save as) changes to one, then save (not save as) different changes to the other, which changes are saved? This could be dangerous.

**Comment by fernandreu** [comment] 2019-11-02 00:19
The changes for which you clicked `Save` last will be saved. Agree it can be quite dangerous, which is why I will include a warning message.

**Closed** 2019-11-02 18:34 UTC
Labels: bug
